# Dependencies
markdown: kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty



# Setup
title:            'Karteek Paladugu'
tagline:          '#include<code>'
url:              https://karteekpaladugu.github.io
baseurl:          "/"



author:
  name:           'Karteek Paladugu'
  url:            https://twitter.com/edorado93
  gravatar_md5:   e24a7e48dce04c5504f30801ef0ca385
  github:         karteekpv77
  linkedin:       karteekpaladugu/
  instagram:      karteekpaladugu/
  gmail:          karteekpv77

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
